/**
 * write long host2netc(long x) in C and let gcc do the work of producing assembly code. 
 * Save the C code in host2netc.c and the assembly code generated by gcc in host2netc.s under system/.
 * Han Wang @ Purdue
 */

//#include <xinu.h>

long host2netca(long x) {
    long result;
    char *x_ptr = ( (char *) &x) + sizeof(long) - 1; // move pointer to the other side
    char *result_ptr = (char *) &result; // move restult pointer to the other side
    //loop through and replace them from end to end
    for (int i = 0; i < sizeof(long); i++) {
        *(result_ptr++) = *(x_ptr--);
    }
    return result;
}
