/**
 * write long host2netc(long x) in C and let gcc do the work of producing assembly code. 
 * Save the C code in host2netc.c and the assembly code generated by gcc in host2netc.s under system/.
 * Han Wang @ Purdue
 */

long host2netc(long x) {
    //TODO
    return 0;
}
